name: test_empty_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:

    sdk: flutter
  flutter_slidable: ^3.0.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  meta: ^1.9.1
  bloc: ^8.1.2
  dio: ^5.5.0+1
  syncfusion_flutter_charts: ^26.2.9
  path: ^1.9.0
  postgres: ^2.2.0
  intl: ^0.19.0
  http: ^1.2.2
  yaml: ^3.1.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.2
  web_socket_channel: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/